version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_my_diary
    ports:
      - "5432:5432"
    networks:
      - nest_development
  postgres-test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_my_diary
    ports:
      - "5433:5432"
    networks:
      - nest_development
networks:
  nest_development:
